export const TIMEZONE_TO_COUNTRY = {
  "Pacific/Midway": "United States",
  "Pacific/Pago_Pago": "American Samoa",
  "Pacific/Honolulu": "United States",
  "America/Juneau": "United States",
  "America/Los_Angeles": "United States",
  "America/Tijuana": "Mexico",
  "America/Denver": "United States",
  "America/Phoenix": "United States",
  "America/Chihuahua": "Mexico",
  "America/Mazatlan": "Mexico",
  "America/Chicago": "United States",
  "America/Regina": "Canada",
  "America/Mexico_City": "Mexico",
  "America/Monterrey": "Mexico",
  "America/Guatemala": "Guatemala",
  "America/New_York": "United States",
  "America/Indiana/Indianapolis": "United States",
  "America/Bogota": "Colombia",
  "America/Lima": "Peru",
  "America/Halifax": "Canada",
  "America/Caracas": "Venezuela",
  "America/La_Paz": "Bolivia",
  "America/Santiago": "Chile",
  "America/St_Johns": "Canada",
  "America/Sao_Paulo": "Brazil",
  "America/Argentina/Buenos_Aires": "Argentina",
  "America/Guyana": "Guyana",
  "America/Godthab": "Greenland",
  "Atlantic/South_Georgia": "South Georgia and the South Sandwich Islands",
  "Atlantic/Azores": "Portugal",
  "Atlantic/Cape_Verde": "Cape Verde",
  "Europe/Dublin": "Ireland",
  "Europe/Lisbon": "Portugal",
  "Europe/London": "United Kingdom",
  "Africa/Casablanca": "Morocco",
  "Africa/Monrovia": "Liberia",
  "Etc/UTC": "Coordinated Universal Time",
  "Europe/Belgrade": "Serbia",
  "Europe/Bratislava": "Slovakia",
  "Europe/Budapest": "Hungary",
  "Europe/Ljubljana": "Slovenia",
  "Europe/Prague": "Czech Republic",
  "Europe/Sarajevo": "Bosnia and Herzegovina",
  "Europe/Skopje": "North Macedonia",
  "Europe/Warsaw": "Poland",
  "Europe/Zagreb": "Croatia",
  "Europe/Brussels": "Belgium",
  "Europe/Copenhagen": "Denmark",
  "Europe/Madrid": "Spain",
  "Europe/Paris": "France",
  "Europe/Amsterdam": "Netherlands",
  "Europe/Berlin": "Germany",
  "Europe/Rome": "Italy",
  "Europe/Stockholm": "Sweden",
  "Europe/Vienna": "Austria",
  "Africa/Algiers": "Algeria",
  "Europe/Bucharest": "Romania",
  "Africa/Cairo": "Egypt",
  "Europe/Helsinki": "Finland",
  "Europe/Kiev": "Ukraine",
  "Europe/Riga": "Latvia",
  "Europe/Sofia": "Bulgaria",
  "Europe/Tallinn": "Estonia",
  "Europe/Vilnius": "Lithuania",
  "Europe/Athens": "Greece",
  "Europe/Istanbul": "Turkey",
  "Europe/Minsk": "Belarus",
  "Asia/Jerusalem": "Israel",
  "Africa/Harare": "Zimbabwe",
  "Africa/Johannesburg": "South Africa",
  "Europe/Volgograd": "Russia",
  "Europe/Moscow": "Russia",
  "Asia/Kuwait": "Kuwait",
  "Asia/Riyadh": "Saudi Arabia",
  "Africa/Nairobi": "Kenya",
  "Asia/Baghdad": "Iraq",
  "Asia/Tehran": "Iran",
  "Asia/Muscat": "Oman",
  "Asia/Baku": "Azerbaijan",
  "Asia/Tbilisi": "Georgia",
  "Asia/Yerevan": "Armenia",
  "Asia/Kabul": "Afghanistan",
  "Asia/Yekaterinburg": "Russia",
  "Asia/Karachi": "Pakistan",
  "Asia/Tashkent": "Uzbekistan",
  "Asia/Kolkata": "India",
  "Asia/Calcutta": "India",
  "Asia/Kathmandu": "Nepal",
  "Asia/Almaty": "Kazakhstan",
  "Asia/Dhaka": "Bangladesh",
  "Asia/Colombo": "Sri Lanka",
  "Asia/Rangoon": "Myanmar (Burma)",
  "Asia/Bangkok": "Thailand",
  "Asia/Jakarta": "Indonesia",
  "Asia/Novosibirsk": "Russia",
  "Asia/Shanghai": "China",
  "Asia/Chongqing": "China",
  "Asia/Hong_Kong": "Hong Kong",
  "Asia/Urumqi": "China",
  "Asia/Kuala_Lumpur": "Malaysia",
  "Asia/Singapore": "Singapore",
  "Asia/Taipei": "Taiwan",
  "Australia/Perth": "Australia",
  "Asia/Irkutsk": "Russia",
  "Asia/Ulaanbaatar": "Mongolia",
  "Asia/Seoul": "South Korea",
  "Asia/Tokyo": "Japan",
  "Asia/Yakutsk": "Russia",
  "Australia/Darwin": "Australia",
  "Australia/Adelaide": "Australia",
  "Australia/Sydney": "Australia",
  "Australia/Brisbane": "Australia",
  "Australia/Hobart": "Australia",
  "Asia/Vladivostok": "Russia",
  "Pacific/Guam": "Guam",
  "Pacific/Port_Moresby": "Papua New Guinea",
  "Asia/Magadan": "Russia",
  "Pacific/Noumea": "New Caledonia",
  "Pacific/Fiji": "Fiji",
  "Asia/Kamchatka": "Russia",
  "Pacific/Majuro": "Marshall Islands",
  "Pacific/Auckland": "New Zealand",
  "Pacific/Tongatapu": "Tonga",
  "Asia/Kuching": "Malaysia",
  "Asia/Pyongyang": "North Korea",
  "Asia/Phnom_Penh": "Cambodia",
  "Asia/Vientiane": "Laos",
  "Africa/Bamako": "Mali",
  "Africa/Djibouti": "Djibouti",
  "Africa/Mogadishu": "Somalia",
  "Africa/Ndjamena": "Chad",
  "Africa/Tunis": "Tunisia",
  "America/Belize": "Belize",
  "America/Cayenne": "French Guiana",
  "America/Curacao": "Curacao",
  "America/El_Salvador": "El Salvador",
  "America/Grand_Turk": "Turks and Caicos Islands",
  "America/Lower_Princes": "Sint Maarten (Dutch part)",
  "America/Marigot": "Saint Martin (French part)",
  "America/Martinique": "Martinique",
  "America/Monaco": "Monaco",
  "America/Port_of_Spain": "Trinidad and Tobago",
  "America/Providence": "Providencia and Santa Catalina",
  "America/Santo_Domingo": "Dominican Republic",
  "America/Scoresbysund": "Greenland",
  "America/St_Barthelemy": "Saint Barthelemy",
  "America/St_Kitts": "Saint Kitts and Nevis",
  "America/St_Lucia": "Saint Lucia",
  "America/St_Thomas": "United States Virgin Islands",
  "America/St_Vincent": "Saint Vincent and the Grenadines",
  "America/Tortola": "British Virgin Islands",
  "America/Anguilla": "Anguilla",
  "Europe/Andorra": "Andorra",
  "Europe/Guernsey": "Guernsey",
  "Europe/Isle_of_Man": "Isle of Man",
  "Europe/Jersey": "Jersey",
  "Europe/Monaco": "Monaco",
  "Europe/Oslo": "Norway",
  "Australia/Currie": "Australia",
  "Australia/Lord_Howe": "Australia",
  "Pacific/Chatham": "New Zealand",
  "Pacific/Enderbury": "Kiribati",
  "Pacific/Funafuti": "Tuvalu",
  "Pacific/Tarawa": "Kiribati",
  "Pacific/Wallis": "Wallis and Futuna",
  "Asia/Choibalsan": "Mongolia",
  "Asia/Anadyr": "Russia",
  "Etc/GMT+12": "Coordinated Universal Time",
};
